### ISSUE TITLE
undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by cbuchler** [dieb/browserlog#18]
Hi, 

I recently installed `browserlog` and I 'm getting the following error. 

`undefined method`[]' for nil:NilClass`

What's the easiest way to fix this error?

**Comment by dieb** [comment]
Could you provide the full traceback?

Thanks

On Fri, Apr 22, 2016 at 9:57 AM, Charles Buchler <notifications@github.com>
wrote:

> Hi,
>
> I recently installed browserlog and I 'm getting the following error.
>
> undefined method[]' for nil:NilClass`
>
> What's the easiest way to fix this error?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/dieb/browserlog/issues/18>
>



-- 
Andre Dieb Martins
andredieb.com

**Comment by cbuchler** [comment]
Hi, 

Sure. 

`Started GET "/logs" for ::1 at 2016-04-22 16:00:52 +0200
  
NoMethodError (undefined method `[]' for nil:NilClass):
  
actionpack (5.0.0.beta3) lib/action_dispatch/journey/router.rb:41:in `block in serve'
actionpack (5.0.0.beta3) lib/action_dispatch/journey/router.rb:26:in `each'
actionpack (5.0.0.beta3) lib/action_dispatch/journey/router.rb:26:in `serve'
actionpack (5.0.0.beta3) lib/action_dispatch/routing/route_set.rb:724:in `call'
actionview (5.0.0.beta3) lib/action_view/digestor.rb:12:in `call'
warden (1.2.6) lib/warden/manager.rb:35:in `block in call'
warden (1.2.6) lib/warden/manager.rb:34:in `catch'
warden (1.2.6) lib/warden/manager.rb:34:in `call'
rack (2.0.0.alpha) lib/rack/etag.rb:25:in `call'
rack (2.0.0.alpha) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.0.alpha) lib/rack/head.rb:12:in `call'
rack (2.0.0.alpha) lib/rack/session/abstract/id.rb:220:in `context'
rack (2.0.0.alpha) lib/rack/session/abstract/id.rb:214:in `call'
actionpack (5.0.0.beta3) lib/action_dispatch/middleware/cookies.rb:613:in `call'
activerecord (5.0.0.beta3) lib/active_record/query_cache.rb:36:in `call'
activerecord (5.0.0.beta3) lib/active_record/connection_adapters/abstract/connection_pool.rb:963:in `call'
activerecord (5.0.0.beta3) lib/active_record/migration.rb:558:in `call'
actionpack (5.0.0.beta3) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (5.0.0.beta3) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.0.beta3) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.0.beta3) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.0.beta3) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (5.0.0.beta3) lib/action_dispatch/middleware/reloader.rb:71:in `call'
actionpack (5.0.0.beta3) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.0.beta3) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
web-console (3.1.1) lib/web_console/middleware.rb:131:in `call_app'
web-console (3.1.1) lib/web_console/middleware.rb:28:in `block in call'
web-console (3.1.1) lib/web_console/middleware.rb:18:in `catch'
web-console (3.1.1) lib/web_console/middleware.rb:18:in `call'
actionpack (5.0.0.beta3) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.0.beta3) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.0.beta3) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.0.beta3) lib/active_support/tagged_logging.rb:70:in `block in tagged'
activesupport (5.0.0.beta3) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.0.beta3) lib/active_support/tagged_logging.rb:70:in `tagged'
railties (5.0.0.beta3) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.0.0.beta3) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.0.alpha) lib/rack/method_override.rb:22:in `call'
rack (2.0.0.alpha) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.0.beta3) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.0.beta3) lib/action_dispatch/middleware/load_interlock.rb:13:in `call'
actionpack (5.0.0.beta3) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.0.alpha) lib/rack/sendfile.rb:111:in `call'
railties (5.0.0.beta3) lib/rails/engine.rb:522:in `call'
puma (3.4.0) lib/puma/configuration.rb:224:in `call'
puma (3.4.0) lib/puma/server.rb:569:in `handle_request'
puma (3.4.0) lib/puma/server.rb:406:in `process_client'
puma (3.4.0) lib/puma/server.rb:271:in `block in run'
puma (3.4.0) lib/puma/thread_pool.rb:114:in `block in spawn_thread'
  Rendered /Users/charles/.rvm/gems/ruby-2.3.0/gems/actionpack-5.0.0.beta3/lib/action_dispatch/middleware/templates/rescues/_source.html.erb (3.9ms)
  Rendered /Users/charles/.rvm/gems/ruby-2.3.0/gems/actionpack-5.0.0.beta3/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (3.0ms)
  Rendered /Users/charles/.rvm/gems/ruby-2.3.0/gems/actionpack-5.0.0.beta3/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.4ms)
  Rendered /Users/charles/.rvm/gems/ruby-2.3.0/gems/actionpack-5.0.0.beta3/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (95.6ms)
  Rendered /Users/charles/.rvm/gems/ruby-2.3.0/gems/web-console-3.1.1/lib/web_console/templates/_markup.html.erb (7.8ms)
  Rendered /Users/charles/.rvm/gems/ruby-2.3.0/gems/web-console-3.1.1/lib/web_console/templates/_inner_console_markup.html.erb within layouts/inlined_string (0.8ms)
  Rendered /Users/charles/.rvm/gems/ruby-2.3.0/gems/web-console-3.1.1/lib/web_console/templates/_prompt_box_markup.html.erb within layouts/inlined_string (0.8ms)
  Rendered /Users/charles/.rvm/gems/ruby-2.3.0/gems/web-console-3.1.1/lib/web_console/templates/style.css.erb within layouts/inlined_string (0.6ms)
  Rendered /Users/charles/.rvm/gems/ruby-2.3.0/gems/web-console-3.1.1/lib/web_console/templates/console.js.erb within layouts/javascript (105.8ms)
  Rendered /Users/charles/.rvm/gems/ruby-2.3.0/gems/web-console-3.1.1/lib/web_console/templates/main.js.erb within layouts/javascript (0.3ms)
  Rendered /Users/charles/.rvm/gems/ruby-2.3.0/gems/web-console-3.1.1/lib/web_console/templates/index.html.erb (199.2ms)

`

I should mention that I'm currently running rails 5 beta3. Is browserlog only supported up to 4.1.1? I may have misunderstood that.

**Comment by dieb** [comment]
At the present moment it only works for Rails <= 4.1.1, I have yet to adapt
it to 5+.

I'll keep this issue updated with the progress :) I have some time to spare
this weekend.

Thanks!

On Fri, Apr 22, 2016 at 10:04 AM, Charles Buchler <notifications@github.com>
wrote:

> Hi,
>
> Sure.
>
> `Started GET "/logs" for ::1 at 2016-04-22 16:00:52 +0200
>
> NoMethodError (undefined method `[]' for nil:NilClass):
>
> actionpack (5.0.0.beta3) lib/action_dispatch/journey/router.rb:41:in block
> in serve'
> actionpack (5.0.0.beta3) lib/action_dispatch/journey/router.rb:26:ineach'
> actionpack (5.0.0.beta3) lib/action_dispatch/journey/router.rb:26:in
> serve'
> actionpack (5.0.0.beta3) lib/action_dispatch/routing/route_set.rb:724:in
> call'
> actionview (5.0.0.beta3) lib/action_view/digestor.rb:12:in call'
> warden (1.2.6) lib/warden/manager.rb:35:inblock in call'
> warden (1.2.6) lib/warden/manager.rb:34:in catch'
> warden (1.2.6) lib/warden/manager.rb:34:incall'
> rack (2.0.0.alpha) lib/rack/etag.rb:25:in call'
> rack (2.0.0.alpha) lib/rack/conditional_get.rb:25:incall'
> rack (2.0.0.alpha) lib/rack/head.rb:12:in call'
> rack (2.0.0.alpha) lib/rack/session/abstract/id.rb:220:incontext'
> rack (2.0.0.alpha) lib/rack/session/abstract/id.rb:214:in call'
> actionpack (5.0.0.beta3) lib/action_dispatch/middleware/cookies.rb:613:in
> call'
> activerecord (5.0.0.beta3) lib/active_record/query_cache.rb:36:in call'
> activerecord (5.0.0.beta3)
> lib/active_record/connection_adapters/abstract/connection_pool.rb:963:in
> call'
> activerecord (5.0.0.beta3) lib/active_record/migration.rb:558:in call'
> actionpack (5.0.0.beta3) lib/action_dispatch/middleware/callbacks.rb:29:inblock
> in call'
> activesupport (5.0.0.beta3) lib/active_support/callbacks.rb:97:in
> __run_callbacks__'
> activesupport (5.0.0.beta3) lib/active_support/callbacks.rb:750:in
> _run_call_callbacks'
> activesupport (5.0.0.beta3) lib/active_support/callbacks.rb:90:in
> run_callbacks'
> actionpack (5.0.0.beta3) lib/action_dispatch/middleware/callbacks.rb:27:in
> call'
> actionpack (5.0.0.beta3) lib/action_dispatch/middleware/reloader.rb:71:in
> call'
> actionpack (5.0.0.beta3) lib/action_dispatch/middleware/remote_ip.rb:79:in
> call'
> actionpack (5.0.0.beta3)
> lib/action_dispatch/middleware/debug_exceptions.rb:49:in call'
> web-console (3.1.1) lib/web_console/middleware.rb:131:incall_app'
> web-console (3.1.1) lib/web_console/middleware.rb:28:in block in call'
> web-console (3.1.1) lib/web_console/middleware.rb:18:incatch'
> web-console (3.1.1) lib/web_console/middleware.rb:18:in call'
> actionpack (5.0.0.beta3)
> lib/action_dispatch/middleware/show_exceptions.rb:31:incall'
> railties (5.0.0.beta3) lib/rails/rack/logger.rb:36:in call_app'
> railties (5.0.0.beta3) lib/rails/rack/logger.rb:24:inblock in call'
> activesupport (5.0.0.beta3) lib/active_support/tagged_logging.rb:70:in block
> in tagged'
> activesupport (5.0.0.beta3) lib/active_support/tagged_logging.rb:26:in
> tagged'
> activesupport (5.0.0.beta3) lib/active_support/tagged_logging.rb:70:in
> tagged'
> railties (5.0.0.beta3) lib/rails/rack/logger.rb:24:incall'
> actionpack (5.0.0.beta3)
> lib/action_dispatch/middleware/request_id.rb:24:in call'
> rack (2.0.0.alpha) lib/rack/method_override.rb:22:incall'
> rack (2.0.0.alpha) lib/rack/runtime.rb:22:in call'
> activesupport (5.0.0.beta3)
> lib/active_support/cache/strategy/local_cache_middleware.rb:28:incall'
> actionpack (5.0.0.beta3)
> lib/action_dispatch/middleware/load_interlock.rb:13:in call'
> actionpack (5.0.0.beta3) lib/action_dispatch/middleware/static.rb:136:in
> call'
> rack (2.0.0.alpha) lib/rack/sendfile.rb:111:in call'
> railties (5.0.0.beta3) lib/rails/engine.rb:522:incall'
> puma (3.4.0) lib/puma/configuration.rb:224:in call'
> puma (3.4.0) lib/puma/server.rb:569:inhandle_request'
> puma (3.4.0) lib/puma/server.rb:406:in process_client'
> puma (3.4.0) lib/puma/server.rb:271:inblock in run'
> puma (3.4.0) lib/puma/thread_pool.rb:114:in `block in spawn_thread'
> Rendered
> /Users/charles/.rvm/gems/ruby-2.3.0/gems/actionpack-5.0.0.beta3/lib/action_dispatch/middleware/templates/rescues/_source.html.erb
> (3.9ms)
> Rendered
> /Users/charles/.rvm/gems/ruby-2.3.0/gems/actionpack-5.0.0.beta3/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb
> (3.0ms)
> Rendered
> /Users/charles/.rvm/gems/ruby-2.3.0/gems/actionpack-5.0.0.beta3/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb
> (1.4ms)
> Rendered
> /Users/charles/.rvm/gems/ruby-2.3.0/gems/actionpack-5.0.0.beta3/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb
> within rescues/layout (95.6ms)
> Rendered
> /Users/charles/.rvm/gems/ruby-2.3.0/gems/web-console-3.1.1/lib/web_console/templates/_markup.html.erb
> (7.8ms)
> Rendered
> /Users/charles/.rvm/gems/ruby-2.3.0/gems/web-console-3.1.1/lib/web_console/templates/_inner_console_markup.html.erb
> within layouts/inlined_string (0.8ms)
> Rendered
> /Users/charles/.rvm/gems/ruby-2.3.0/gems/web-console-3.1.1/lib/web_console/templates/_prompt_box_markup.html.erb
> within layouts/inlined_string (0.8ms)
> Rendered
> /Users/charles/.rvm/gems/ruby-2.3.0/gems/web-console-3.1.1/lib/web_console/templates/style.css.erb
> within layouts/inlined_string (0.6ms)
> Rendered
> /Users/charles/.rvm/gems/ruby-2.3.0/gems/web-console-3.1.1/lib/web_console/templates/console.js.erb
> within layouts/javascript (105.8ms)
> Rendered
> /Users/charles/.rvm/gems/ruby-2.3.0/gems/web-console-3.1.1/lib/web_console/templates/main.js.erb
> within layouts/javascript (0.3ms)
> Rendered
> /Users/charles/.rvm/gems/ruby-2.3.0/gems/web-console-3.1.1/lib/web_console/templates/index.html.erb
> (199.2ms)
>
> `
>
> I should mention that I'm currently running rails 5 beta3. Is browserlog
> only supported up to 4.1.1? I may have misunderstood that.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/dieb/browserlog/issues/18#issuecomment-213441359>
>



-- 
Andre Dieb Martins
andredieb.com

**Comment by cbuchler** [comment]
Hey, 

Thank you for your work @dieb !

If you need any testing, let me know I'd love to help

**Comment by cbuchler** [comment]
Any progress so far?

**Comment by mibamur** [comment]
rails 5 still not worked

**Comment by cbuchler** [comment]
Closing as it's not relevant anymore.
